=== Vlady32/xmlTask/jse8/xmlTask/src/test/resources/DTDPhoneBook.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT persons (person)*>
<!ELEMENT person (fullName, address+, telephone+)>
<!ATTLIST person 
	id ID #REQUIRED
>
<!ELEMENT fullName (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>

=== Vlady32/xmlTask/jse8/xmlTask/src/test/resources/testPhoneBook.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE persons SYSTEM "C:\Users\Vlady\git\xmlTask\jse8\xmlTask\src\main\resources\DTDPhoneBook.dtd">
<persons>
  <person id="p1">
    <fullName>Kolotsey Vladislav Vladzimirovich</fullName>
    <address>Bobruisk Batova sreet 18-18</address>
    <telephone>80445564654</telephone>
  </person>
  <person id="p2">
    <fullName>Melnikov Konstantin</fullName>
    <address>Gomel Sovetskaya sreet 52-11</address>
    <telephone>80445653456</telephone>
  </person>
















































































































</persons>

=== Vlady32/xmlTask/jse8/xmlTask/src/test/resources/anotherNotValidTestPhoneBook.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persons SYSTEM "DTDPhoneBook.dtd">
<persons>
  <person id="p1">
    <fullName>Lotish Dmitry</fullName>
    <address>Bobruisk Batova sreet 18-18</address>
    <telephone>80445564654</telephone>
  </person>
  <person id="2">
    <fullName>Klimenkov Andrei</fullName>
    <address>Gomel Sovetskaya sreet 52-11</address>
    <telephone>80445653456</telephone>
  </person>






















</persons>
